#include <stdio.h>
#include <string.h>

char *instr[] = {"jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "jmp ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "acc ",
                 "nop ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "acc ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "jmp ",
                 "nop ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "nop ",
                 "nop ",
                 "nop ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "nop ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "nop ",
                 "jmp ",
                 "nop ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "nop ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp ",
                 "acc ",
                 "nop ",
                 "nop ",
                 "nop ",
                 "jmp ",
                 "jmp ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "acc ",
                 "jmp "};

int operand[] = {
    27,
    32,
    10,
    23,
    88,
    46,
    -3,
    209,
    1,
    159,
    29,
    328,
    44,
    14,
    14,
    557,
    127,
    34,
    227,
    214,
    512,
    78,
    544,
    14,
    5,
    -11,
    291,
    5,
    115,
    166,
    2,
    1,
    500,
    244,
    186,
    43,
    26,
    502,
    14,
    63,
    115,
    -11,
    153,
    3,
    107,
    468,
    -6,
    38,
    0,
    102,
    27,
    -9,
    45,
    186,
    457,
    14,
    483,
    35,
    27,
    202,
    -55,
    1,
    33,
    -2,
    5,
    296,
    17,
    11,
    36,
    11,
    10,
    20,
    115,
    37,
    284,
    39,
    40,
    1,
    1,
    233,
    42,
    27,
    1,
    189,
    329,
    118,
    13,
    -82,
    18,
    -1,
    23,
    104,
    25,
    5,
    49,
    274,
    35,
    1,
    45,
    -1,
    128,
    110,
    11,
    48,
    316,
    -15,
    150,
    396,
    19,
    15,
    129,
    17,
    42,
    1,
    13,
    333,
    -24,
    5,
    -9,
    -14,
    129,
    14,
    486,
    -4,
    274,
    269,
    0,
    36,
    8,
    -102,
    -3,
    18,
    162,
    16,
    26,
    313,
    9,
    -26,
    16,
    383,
    10,
    245,
    119,
    -57,
    17,
    75,
    13,
    452,
    -13,
    -13,
    -115,
    18,
    97,
    0,
    -28,
    43,
    401,
    -17,
    91,
    16,
    22,
    42,
    244,
    376,
    36,
    20,
    32,
    -157,
    -6,
    33,
    295,
    -20,
    -2,
    7,
    305,
    -76,
    18,
    24,
    89,
    -8,
    -1,
    171,
    40,
    11,
    15,
    43,
    234,
    1,
    45,
    343,
    -140,
    40,
    -6,
    35,
    67,
    -5,
    2,
    32,
    32,
    199,
    40,
    19,
    337,
    -1,
    -14,
    34,
    266,
    265,
    -1,
    31,
    151,
    -206,
    49,
    24,
    -16,
    -82,
    -117,
    238,
    -10,
    150,
    26,
    -95,
    21,
    59,
    -13,
    45,
    45,
    350,
    285,
    28,
    31,
    6,
    -106,
    294,
    -142,
    13,
    347,
    43,
    79,
    7,
    368,
    35,
    1,
    4,
    355,
    -10,
    -175,
    35,
    -3,
    -2,
    35,
    33,
    34,
    -154,
    27,
    131,
    -18,
    74,
    -14,
    173,
    79,
    -82,
    26,
    -4,
    -237,
    270,
    118,
    0,
    34,
    -212,
    -59,
    -150,
    26,
    224,
    1,
    -18,
    85,
    -134,
    6,
    -136,
    4,
    -246,
    9,
    24,
    -105,
    99,
    -13,
    -15,
    286,
    -187,
    -276,
    -14,
    -12,
    148,
    -18,
    -254,
    23,
    -10,
    32,
    49,
    39,
    -10,
    10,
    -17,
    39,
    19,
    236,
    -205,
    0,
    5,
    -15,
    41,
    28,
    -18,
    -20,
    -175,
    23,
    36,
    198,
    223,
    1,
    -60,
    28,
    118,
    12,
    9,
    159,
    176,
    11,
    -1,
    183,
    -6,
    16,
    -43,
    -17,
    222,
    -4,
    1,
    -21,
    43,
    42,
    -2,
    12,
    168,
    10,
    38,
    -159,
    94,
    5,
    -1,
    -317,
    -294,
    42,
    11,
    38,
    27,
    0,
    -63,
    -57,
    23,
    -111,
    1,
    -12,
    -91,
    22,
    -1,
    -163,
    1,
    -165,
    -12,
    -7,
    -9,
    37,
    82,
    -10,
    29,
    0,
    200,
    -129,
    13,
    33,
    -33,
    27,
    -172,
    57,
    -234,
    -141,
    35,
    202,
    -6,
    51,
    10,
    -8,
    -291,
    36,
    25,
    -263,
    211,
    21,
    -7,
    -6,
    -222,
    -247,
    -8,
    29,
    -21,
    0,
    -256,
    1,
    37,
    55,
    40,
    -266,
    17,
    200,
    1,
    7,
    10,
    24,
    -6,
    8,
    -104,
    -64,
    3,
    -391,
    26,
    6,
    12,
    -9,
    110,
    -420,
    -411,
    -273,
    -287,
    39,
    117,
    -119,
    38,
    119,
    0,
    -430,
    -14,
    -231,
    26,
    1,
    -13,
    15,
    -208,
    1,
    50,
    -263,
    14,
    1,
    31,
    -13,
    -334,
    76,
    -435,
    -52,
    131,
    53,
    19,
    -213,
    5,
    -338,
    48,
    22,
    43,
    1,
    -377,
    38,
    -268,
    -269,
    20,
    6,
    -395,
    -415,
    1,
    -398,
    -12,
    -10,
    -18,
    1,
    94,
    -358,
    -313,
    12,
    20,
    -13,
    -110,
    28,
    12,
    42,
    43,
    101,
    -14,
    -6,
    25,
    -7,
    5,
    -420,
    -4,
    -89,
    -17,
    -499,
    -379,
    -395,
    37,
    30,
    5,
    -25,
    63,
    71,
    -3,
    -24,
    -117,
    -6,
    1,
    26,
    -212,
    -498,
    -395,
    -210,
    44,
    12,
    21,
    40,
    43,
    -382,
    -509,
    -17,
    -111,
    -16,
    31,
    -306,
    -22,
    50,
    47,
    -398,
    -300,
    -246,
    49,
    0,
    12,
    7,
    -6,
    -109,
    -19,
    21,
    -19,
    -355,
    -418,
    -245,
    50,
    1,
    -3,
    -177,
    29,
    40,
    -15,
    -123,
    -305,
    -313,
    -3,
    50,
    -530,
    -398,
    16,
    29,
    -358,
    37,
    -165,
    -193,
    -132,
    21,
    -355,
    -450,
    -456,
    25,
    49,
    50,
    0,
    -60,
    5,
    -15,
    -565,
    10,
    -9,
    -3,
    -220,
    44,
    -10,
    -70,
    -17,
    -174,
    -168,
    6,
    35,
    -133,
    -12,
    41,
    41,
    -580,
    45,
    27,
    12,
    0,
    -24,
    35,
    -507,
    -27,
    -456,
    -379,
    -222,
    6,
    43,
    -9,
    45,
    1};

int d8part1(void);
void d8part2(void);

int main(void)
{

    // d8part1();
    d8part2();

    return (1);
}

void d8part2(void)
{

    int index = 0, result;

    char *copy_instr[619];

    memcpy(copy_instr, instr, 619);

    // while (index < 619)              
    {

        if (strcmp(instr[index], "acc ") != 0)
        {
            if (strcmp(instr[index], "jmp ") == 0)
            {
                strcpy(instr[index], "nop ");
            }
            else
            {
                strcpy(instr[index], "jmp ");
            }

            result = d8part1();
            printf("%d", result);
        }

        // index++;
        // memcpy(instr, copy_instr, 619);
    }
}

int d8part1(void)
{

    int instr_index = 0, accumulator = 0;
    int prev_instr_index[619] = {0};

    // memset(prev_instr_index, 0, (sizeof(prev_instr_index) / sizeof(prev_instr_index[0])));

    while (1)
    {

        // printf("%d\n", prev_instr_index[instr_index]);

        if (strcmp(instr[instr_index], "nop ") == 0)
        {
            if (prev_instr_index[instr_index] == 0)
            {
                prev_instr_index[instr_index] = 1;
                instr_index++;
            }
            else
            {
                break;
            }
            // printf("%d %d\n", instr_index, prev_instr_index[instr_index]);
        }
        if (strcmp(instr[instr_index], "jmp ") == 0)
        {
            if (prev_instr_index[instr_index] == 0)
            {
                prev_instr_index[instr_index] = 1;
                instr_index = instr_index + operand[instr_index];
            }
            else
            {
                break;
            }
            // printf("%d %d\n", instr_index, prev_instr_index[instr_index]);
        }
        if (strcmp(instr[instr_index], "acc ") == 0)
        {
            if (prev_instr_index[instr_index] == 0)
            {
                prev_instr_index[instr_index] = 1;
                accumulator = accumulator + operand[instr_index];
                instr_index++;
            }
            else
            {
                break;
            }
            // printf("%d %d\n", instr_index, prev_instr_index[instr_index]);
        }
    };

    printf("%d\n", accumulator);
    return (instr_index);
}